name: ${CrystalZero}
version: ${1.19.3}
author: pajama
authors: [pajama, fxcilitites, totemo, bermudalocket]
description: ${stop players from placing crystals}
website: ${project.url}
main: nu.nerd.safecrystals.SafeCrystals
api-version: 1.15

depend: [WorldGuard]

permissions: {}

commands: {}

